export enum Object {
	NULL = 'NULL',
	WALL = 'WALL',
	PLAYER = 'PLAYER',
	WATER = 'WATER',
	LAVA = 'LAVA',
	FINISH = 'FINISH',
	APPLE = 'APPLE',
	PEAR = 'PEAR',
	PORTAL = 'PORTAL',
	BOX = 'BOX',
	GIFT_BOX = 'GIFT_BOX',
	BAD_APPLE = 'BAD_APPLE'
}
